package org.fossify.gallery.compose.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF6D5E00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFE26D)
val md_theme_light_onPrimaryContainer = Color(0xFF221B00)
val md_theme_light_secondary = Color(0xFF655E40)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFEDE2BC)
val md_theme_light_onSecondaryContainer = Color(0xFF201C04)
val md_theme_light_tertiary = Color(0xFF42664E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC4ECCE)
val md_theme_light_onTertiaryContainer = Color(0xFF002110)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1D1B16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1D1B16)
val md_theme_light_surfaceVariant = Color(0xFFE8E2D0)
val md_theme_light_onSurfaceVariant = Color(0xFF4A4639)
val md_theme_light_outline = Color(0xFF7B7667)
val md_theme_light_outlineVariant = Color(0xFFCCC6B5)
val md_theme_light_outline_dark = Color(0xFF969080)
val md_theme_dark_primary = Color(0xFFE3C53A)
val md_theme_dark_onPrimary = Color(0xFF3A3000)
val md_theme_dark_primaryContainer = Color(0xFF534600)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFE26D)
val md_theme_dark_secondary = Color(0xFFD0C6A2)
val md_theme_dark_onSecondary = Color(0xFF353018)
val md_theme_dark_secondaryContainer = Color(0xFF4D472B)
val md_theme_dark_onSecondaryContainer = Color(0xFFEDE2BC)
val md_theme_dark_tertiary = Color(0xFFA9D0B3)
val md_theme_dark_onTertiary = Color(0xFF143723)
val md_theme_dark_tertiaryContainer = Color(0xFF2B4F38)
val md_theme_dark_onTertiaryContainer = Color(0xFFC4ECCE)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1D1B16)
val md_theme_dark_onBackground = Color(0xFFE8E2D0)
val md_theme_dark_surface = Color(0xFF1D1B16)
val md_theme_dark_onSurface = Color(0xFFE8E2D0)
val md_theme_dark_surfaceVariant = Color(0xFF4A4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFCCC6B5)
val md_theme_dark_outlineVariant = Color(0xFF49453A)

// Surface-container tonal steps and inverse roles, completing the custom scheme above. Without
// these, Material3's lightColorScheme()/darkColorScheme() factories silently fall back to the
// library's baseline (unrelated) palette for any role not passed explicitly - visible as an
// off-hue NavigationBar/TopAppBar/UndoBar whenever dynamic color is off. Tones are hand-picked to
// sit in the same warm-neutral family as the existing surface/surfaceVariant/background colors
// above rather than computed from the true HCT tonal-palette algorithm.
val md_theme_light_surfaceDim = Color(0xFFDED8CB)
val md_theme_light_surfaceBright = Color(0xFFFFFBFF)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFF8F2E5)
val md_theme_light_surfaceContainer = Color(0xFFF2ECDF)
val md_theme_light_surfaceContainerHigh = Color(0xFFECE6D9)
val md_theme_light_surfaceContainerHighest = Color(0xFFE6E0D3)
val md_theme_light_inverseSurface = Color(0xFF322F27)
val md_theme_light_inverseOnSurface = Color(0xFFF5EFDF)
val md_theme_light_inversePrimary = md_theme_dark_primary

val md_theme_dark_surfaceDim = Color(0xFF1D1B16)
val md_theme_dark_surfaceBright = Color(0xFF433F35)
val md_theme_dark_surfaceContainerLowest = Color(0xFF120F0A)
val md_theme_dark_surfaceContainerLow = Color(0xFF26231D)
val md_theme_dark_surfaceContainer = Color(0xFF2A2721)
val md_theme_dark_surfaceContainerHigh = Color(0xFF34302A)
val md_theme_dark_surfaceContainerHighest = Color(0xFF3F3B34)
val md_theme_dark_inverseSurface = Color(0xFFE8E2D0)
val md_theme_dark_inverseOnSurface = Color(0xFF322F27)
val md_theme_dark_inversePrimary = md_theme_light_primary
